apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
  namespace: aaa
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-03080ab6e36bf3a0d