kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: aaa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-static