apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: envars-demo-container
      image: gcr.io/google-samples/node-hello:1.0
      env:
        - name: DEMO_GREETING
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: user 
        - name: DEMO_BYE
          value: "Have a nice day"
  volumes:
    - name: config-volume
      secret:
        secretName: mysecret
        items:
          - password
      configMap:
        name: template
        items:
          - game-special-key.temp2
