apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: my-busybox
spec:
  containers:
    - name: my-busybox-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "echo Hello K8S && sleep 600"
  