apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: server
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50