apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world
  namespace: study
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: hello-world
          restartPolicy: OnFailure