apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  namespace: study
spec:
  template:
    spec:
      containers:
        - name: hello
          image: hello-world
      restartPolicy: Never
  backoffLimit: 2
