apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: study
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      env:
        - name: LOGIN
          valueFrom:
            secretKeyRef:
              name: secret
              key: login
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
  restartPolicy: Never
