apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: study
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      volumeMounts:
        - name: vol
          mountPath: "/etc/vol"
          readOnly: true
  volumes:
    - name: vol
      secret:
        secretName: secret
        items:
          - key: login
            path: login
  restartPolicy: Never