apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: study
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      envFrom:
        - configMapRef:
            name: config
      ports:
        - containerPort: 80